enum Genre {
	'action' = 'Action',
	'drama' = 'Drame',
	'c0m1dy' = 'Comédie',
	'adventure' = 'Aventure',
	'mystery' = 'Mystère',
	'slice of life' = 'Slice of life',
	'sci-fi' = 'Sci-fi',
	'fantasy' = 'Fantasy',
	'psychological' = 'Psychologique',
	'magic' = 'Magie',
	'horror' = 'Horreur',
	'romance' = 'Romance',
	'battle royale' = 'Battle royale',
	'music' = 'Musique',
	'sports' = 'Sport',
	'shounen' = 'Shounen',
	'cyberpunk' = 'Cyberpunk',
	'ecchi' = 'Ecchi',
	'military' = 'Militaire',
	'mecha' = 'Mecha',
	'supernatural' = 'Supernatural',
	'mafia' = 'Mafia',
	'shoujo' = 'Shoujo',
	'isekai' = 'Isekai',
	'mahou shoujo' = 'Mahou shoujo',
}

export default Genre;
